---
title: "week 2 - assignment.rmd"
author: "Robin Scheuplein"
date: "`r Sys.Date()`"
output: html_document
---

```{r, library }
# Load AnnotationHub library
library(BiocFileCache)
library(dbplyr)
library(AnnotationHub)
library(ensembldb)
library(GenomicRanges)
library(epiwraps)
library(ggplot2)
```

```{r,connect}
# Connect to AnnotationHub
ah <- AnnotationHub()
```


```{r}
# Search and download drosophila melanogaster genome sequence (dna_sm) in TwoBit/2bit format for BDGP6
drosophila_genome <- query(ah, c("2bit", "Drosophila melanogaster", "BDGP6", "dna_sm"))
```

```{r}
# Search and download mouse genome sequence (dna_sm) in TwoBit/2bit format for GRCm38
mouse_genome <- query(ah, c("2bit", "Mus musculus", "GRCm38", "dna_sm"))
```

```{r, mouse}
# Search and download mouse EnsDb object, version 102, genome build GRCm38
mouse_ensdb <- query(ah, c("ensembl", "Mus musculus", "102", "GRCm38"))
```

```{r}
# How many different Ensembl gene IDs and gene symbols are there for protein-coding genes?
# Extract protein-coding genes
mouseensdb <- ah[["AH89211"]] # Load the EnsDb object
genes <- genes(mouseensdb)
proteinCodingGenes <- genes(mouseensdb, filter = GeneBiotypeFilter("protein_coding"))
numGeneIDs <- length(unique(proteinCodingGenes$gene_id))
numGeneSymbols <- length(unique(proteinCodingGenes$gene_name))

print(paste("Number of unique Ensembl gene IDs: ", numGeneIDs))
print(paste("Number of unique gene symbols: ", numGeneSymbols))
```

```{r}
# Extract exons of protein-coding transcript
exons <- exonsBy(mouseensdb, by = "tx", filter = GeneBiotypeFilter("protein_coding"))
```

```{r}
# Calculate the (spliced) length of protein-coding transcripts
transcript_lengths <- sapply(width(exons), sum)
```

```{r}
# Plot the distribution of the (spliced) length of protein-coding transcripts
ggplot2::ggplot(data.frame(Length = transcript_lengths), aes(x = Length)) +
  geom_histogram(binwidth = 100, color = "black", fill = "white") +
  theme_minimal() +
  xlim(c(0,25000))
  labs(x = "Transcript length (bp)", y = "Frequency", title = "Distribution of protein-coding transcript lengths")
```

```{r}
# Plot the distribution of the (spliced) length of protein-coding transcripts 2.0
transcript_lengths <- as.numeric(transcript_lengths)
hist(transcript_lengths, breaks = 300, xlim = c(0,15000), xlab = "Transcript Length")
```


